### ISSUE TITLE
Font and background color are both white in Mac-Os

### ISSUE THREAD

**Issue by nick-walkden** [euratom-software/calcam#37]
Both the font and background color are white in selection menus, see image.

![screenshot 2019-02-07 at 15 16 39](https://user-images.githubusercontent.com/5685597/52421187-7596a980-2aeb-11e9-8d87-af83ce90037a.png)

**Comment by ssilburn** [comment]
Hi Nick, (I know we spoke about this but wanted to write it down here). As far as I can tell this is due to a general problem with Qt and OSX dark theme; the font colours etc are not explicitly set by Calcam. From some research it looks like it should be fixed in Qt 5.12, but I'll leave this issue open for now in case it isn't. If you get PyQt 5.12 please report back whether that fixes this not!

**Comment by ssilburn** [comment]
Hi Nick, is this still happening?

**Comment by ssilburn** [comment]
In the absence of any evidence this is still happening or any way for me to test it, because this has been sitting here idle for ages, I'm going to close this issue. I'll keep the warning in the documentation that this happens with PyQt < 5.12, hopefully it was actually fixed in 5.12 but I have no way of checking.
