### ISSUE TITLE
Distinguish raycast rays that don't intersect surfaces

### ISSUE THREAD

**Issue by TomFarley** [euratom-software/calcam#49]
Currently if a raycast point passes through a port or hole in the CAD model, the length of the returned ray is a function of the CAD dimensions and can be confusing to the user. It would be helpful if these ray lengths and end coords are returned as eg nans.

**Comment by ssilburn** [comment]
Hi Tom,

This is added in v2.5 - there is a new boolean keyworkd argument to raycast_sightlines() called "inersecting_only" - if you set this to True, rays which don't hit the CAD geometry will get NaN end coordinates and lengths. The default behaviour is still the same (default value of intersecting_only is False) because (1) to not break backwards compatibility, and (2) because the original behaviour is the desirable one in other uses cases e.g. generating tomography matrices.
